### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by gavanderhoorn** [arminstitute/industrial_payload_manager#2]
The [package manifest](https://github.com/arminstitute/industrial_payload_manager/blob/63721531f90d93c2cd63e0c9f6aa11f5d520cb83/industrial_payload_manager/package.xml) seems to be missing quite a few run/exec dependencies, such as `resource_retriever`, `visualization_msgs`, `urdf_parser_py` and `general_robotics_toolbox` (those are from `industrial_payload_manager.py`, haven't checked the other scripts yet).

This makes installation/setup of a workspace fail at the moment (or at least: running things fails as dependencies are not present).

**Comment by johnwason** [comment]
I will check what packages are required against a clean ROS install.

**Comment by johnwason** [comment]
Fixed in e7ba8ba

**Comment by gavanderhoorn** [comment]
FYI: `tf` is deprecated. New code should use `tf2`.
